version: 2
jobs:
  build:
    docker:
      - image: hed:0.1
    steps:
      - checkout 
      - run:
          name: Run Tests
          command: python3.6 -m unittest test_rpc_call.TestSuiteGrpc
          

workflows:
  version: 2
  build_and_test:
    jobs:
      - build